### ISSUE TITLE
Issue and Suggestion

### ISSUE THREAD

**Issue by RaphaelDDL** [marcelomazza/caniuse-chrome-extension#1]
Hello there,

First gotta thank you for taking your time making the extension, very useful!

I'd like to report an issue and make a suggestion.

issue :
Version table is very buggy, order-wise.
For e.g.: Searching for `min` -> `min/max-width/height`, I see the following:

![ciuext](https://f.cloud.github.com/assets/1087109/518392/5c578b44-befc-11e2-9a43-8758bcb34855.png)
- IE - starts at 6, the last one is 5.5 (Shouldn't be before 6?)
- FF - starts at 2, have 3, 4, etc and ends with 3.5 and 3.6
- Chrome - Okay.
- Safari - starts at 4, ends with 3.1, 3.2, 5.1?
- iOS - Starts at 6, then goes the correct order

If you go to http://caniuse.com/#feat=minmaxwh, the order is correct

![ciuweb](https://f.cloud.github.com/assets/1087109/518393/60ed6d86-befc-11e2-8d5f-0c0f94bcdf24.png)

It's possible to fix the order? And this question also is my suggestion:

So could you make the **current** version be the first and then, the previous ones below? [INVERT the sort (after you fixed the versions)]

My point:
Since there are lots of versions (specially Chrome and FF), the search result always have scroll.  Since people usually tend to support mostly the current versions + 2 or 3 version older to the current, the most important info is the current and the ones before, not the oldest ones.

So the important info is displayed as the search result is displayed, no needing to scroll, unless the person is actually interested.

As for the layout to be visible that the first is the current, add a new reference with light yellow with 'current version' and add the color to the first table row.

Thanks for your time and let me know what you think.

Best Regards,
RaphaelDDL

**Comment by marcelomazza** [comment]
@RaphaelDDL hi! You filled this issue in 2013 and I only notice it now! Better late than sorry.

The updates to the extension kind of solve the issues you mention, now only the most popular browsers are shown. Thanks for your awesome feedback!
