### ISSUE TITLE
Last column (opera mobile) is different to the webseite column

### ISSUE THREAD

**Issue by Chris2011** [marcelomazza/caniuse-chrome-extension#2]
As you can see in my screenshot, on the website there is IE mobile, on your extension there is Opera mobile. Its not only the icon, the whole column is wrong. Maybe you can add IE mobile too or change opera mobile to ie mobile.
![ieopera](https://cloud.githubusercontent.com/assets/795658/3184654/1758a69e-ec88-11e3-9e94-29e028fae5d6.png)

Regards

Chris

**Comment by Chris2011** [comment]
Normally, I see 10 columns, when I click on show all versions, I got 13 results.

**Comment by marcelomazza** [comment]
Hi @Chris2011! I only noticed this issue now (yes, 3 years later).

The data has been updated of course, so this one should be fixed by now. Thanks for the feedback!

**Comment by Chris2011** [comment]
Thx would be great to use it soon again :)

**Comment by Chris2011** [comment]
Would be better to close the ticket after it was fixed, only a hint ;)
